---
title: "GMM + LSS"
author: "Kohei Watanabe"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi = 150, fig.width = 10)
source("settings.R")
library(ggplot2)
library(LSX)

file <- list.files(file.path(DIR_RESULT, "/lss"), pattern = "^data_", full.names = TRUE)
dat <- do.call(rbind, lapply(file, readRDS))
dat
```

```{r}
boxplot(lss ~ country, dat, las = 2)
```

```{r}
smo <- smooth_lss(dat, "lss", group = "country", engine = "locfit")
ggplot(smo, aes(date, fit, color = country)) +
  geom_line()
```

```{r}
dat_ph <- subset(dat, country == "ph")
smo_ph <- smooth_lss(dat_ph, "lss", group = "source_id", engine = "locfit")
ggplot(smo_ph, aes(date, fit, color = source_id)) +
  geom_line()
```

```{r}
ggplot(subset(dat, country == "ph"), aes(date, lss, color = source_id)) +
  stat_summary(fun = "mean", geom = "line") 
```

```{r}
ggplot(subset(dat, country == "id"), aes(date, lss, color = source_id)) +
  stat_summary(fun = "mean", geom = "line") 
```

```{r}
ggplot(subset(dat, country == "ve"), aes(date, lss, color = source_id)) +
  stat_summary(fun = "mean", geom = "line") 
```

