ir: 
  - tasnimnews # ended in January 2026
  - tasnimnews_ir
  - mehrnews
  - irna

gb: 
  #- mirroruk
  - standarduk
  - theguardian

us:
  - theepochtimes
  - washingtontimes
            
lb:
  - almanar
  - tayyar
  - manartv_lb
  
iq:
  - non14
  - almadapaper
  - azzaman
  - alsabaah_iq
  
il:
  - haaretz
  - ynet_co

ps:
  - palinfo
  - pnn_ps
  
ph: 
  - inquirer # Philippine Daily Inquirer (liberal)
  - mb # Manila Bulletin (pro-government)
  - philstar
  - rappler
  #- bandera_inquirer # Filipino
  #- tribune # Filipino

id: 
  - mediaindonesia # Media Indonasia
  - republikain # Republika
  - kompas # low coverage
  - detik # Detik
  - liputan6 # Liputan6
  - tribunnews
my:
  - kosmo
  - sinarharian
  - hmetro
  - utusan

vn:
  - dantri_vn
  - h24_vn
  - vnexpress
  - danviet

  
cn:
  - 81cn # Chinese Military
  - voc_cn # Voice of China
  - people_cn
  - bjnews
  # - en_people_cn # English
  # - xinhuanet  # English
  


